version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules # node_modules는 컨테이너 내부 것 유지
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    command: npm run dev
    environment:
      - MONGO_URI=mongodb://mongo:27017/myboard

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start 

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

